"""Physical constants and unit conversions used across the application."""

NIST_CONSTANTS = {
    "EV_TO_KCAL_MOL": 23.060549286,
    "HARTREE_TO_KCAL_MOL": 627.509474,
    "HARTREE_TO_EV": 27.211386245988,
    "R_KCAL_MOL_K": 0.00198720425864083,
    "DEFAULT_TEMPERATURE_K": 350.0
}

HARTREE_TO_KCAL_MOL = NIST_CONSTANTS["HARTREE_TO_KCAL_MOL"]
HARTREE_TO_EV = NIST_CONSTANTS["HARTREE_TO_EV"]
R_KCAL_MOL_K = NIST_CONSTANTS["R_KCAL_MOL_K"]
DEFAULT_TEMPERATURE_K = NIST_CONSTANTS["DEFAULT_TEMPERATURE_K"]

ALLOWED_UPLOAD_EXTENSIONS = {".log", ".out", ".gjf", ".com", ".xyz", ".csv", ".json", ".cube", ".cub"}
